import random


INSTAGRAM_QUOTES = [
    {"q": "The journey of a thousand miles begins with one step.", "a": "Lao Tzu"},
    {"q": "What you do every day matters more than what you do once in a while.", "a": "Gretchen Rubin"},
    {"q": "Well begun is half done.", "a": "Aristotle"},
    {"q": "He who has a why to live can bear almost any how.", "a": "Friedrich Nietzsche"},
    {"q": "Act as if what you do makes a difference. It does.", "a": "William James"},
    {"q": "Energy and persistence conquer all things.", "a": "Benjamin Franklin"},
    {"q": "Do what you can, with what you have, where you are.", "a": "Theodore Roosevelt"},
    {"q": "It always seems impossible until it is done.", "a": "Nelson Mandela"},
    {"q": "Dreams grow if you grow.", "a": "Zig Ziglar"},
    {"q": "The secret of getting ahead is getting started.", "a": "Mark Twain"},
    {"q": "No great thing is created suddenly.", "a": "Epictetus"},
    {"q": "If you want to lift yourself up, lift up someone else.", "a": "Booker T. Washington"},
    {"q": "The future depends on what you do today.", "a": "Mahatma Gandhi"},
    {"q": "Quality is not an act, it is a habit.", "a": "Aristotle"},
    {"q": "Believe you can and you are halfway there.", "a": "Theodore Roosevelt"},
    {"q": "Turn your wounds into wisdom.", "a": "Oprah Winfrey"},
    {"q": "Great works are performed not by strength but by perseverance.", "a": "Samuel Johnson"},
    {"q": "If there is no struggle, there is no progress.", "a": "Frederick Douglass"},
    {"q": "You miss 100 percent of the shots you do not take.", "a": "Wayne Gretzky"},
    {"q": "The only way to do great work is to love what you do.", "a": "Steve Jobs"},
    {"q": "Stay hungry, stay foolish.", "a": "Steve Jobs"},
    {"q": "Nothing will work unless you do.", "a": "Maya Angelou"},
    {"q": "A goal without a plan is just a wish.", "a": "Antoine de Saint-Exupery"},
    {"q": "If opportunity does not knock, build a door.", "a": "Milton Berle"},
    {"q": "The best revenge is massive success.", "a": "Frank Sinatra"},
    {"q": "You must do the thing you think you cannot do.", "a": "Eleanor Roosevelt"},
    {"q": "Happiness depends upon ourselves.", "a": "Aristotle"},
    {"q": "Simplicity is the ultimate sophistication.", "a": "Leonardo da Vinci"},
    {"q": "The harder the conflict, the greater the triumph.", "a": "George Washington"},
    {"q": "To improve is to change; to be perfect is to change often.", "a": "Winston Churchill"},
    {"q": "Success is the sum of small efforts, repeated day in and day out.", "a": "Robert Collier"},
    {"q": "Do not wait. The time will never be just right.", "a": "Napoleon Hill"},
    {"q": "Action is the foundational key to all success.", "a": "Pablo Picasso"},
    {"q": "A wise man will make more opportunities than he finds.", "a": "Francis Bacon"},
    {"q": "Either you run the day or the day runs you.", "a": "Jim Rohn"},
    {"q": "The mind is everything. What you think you become.", "a": "Buddha"},
    {"q": "Courage is grace under pressure.", "a": "Ernest Hemingway"},
    {"q": "The roots of education are bitter, but the fruit is sweet.", "a": "Aristotle"},
    {"q": "Doubt kills more dreams than failure ever will.", "a": "Suzy Kassem"},
    {"q": "The best way out is always through.", "a": "Robert Frost"},
    {"q": "With the new day comes new strength and new thoughts.", "a": "Eleanor Roosevelt"},
    {"q": "To be prepared is half the victory.", "a": "Miguel de Cervantes"},
    {"q": "If you can dream it, you can do it.", "a": "Walt Disney"},
    {"q": "Whatever you are, be a good one.", "a": "Abraham Lincoln"},
    {"q": "The only limit to our realization of tomorrow is our doubts of today.", "a": "Franklin D. Roosevelt"},
    {"q": "The best preparation for tomorrow is doing your best today.", "a": "H. Jackson Brown Jr."},
    {"q": "Try not to become a person of success, but rather a person of value.", "a": "Albert Einstein"},
    {"q": "In the middle of difficulty lies opportunity.", "a": "Albert Einstein"},
    {"q": "Lost time is never found again.", "a": "Benjamin Franklin"},
    {"q": "Knowing yourself is the beginning of all wisdom.", "a": "Aristotle"},
]


def get_instagram_quote():
    return random.choice(INSTAGRAM_QUOTES)
