import random


INSTAGRAM_QUOTES = [
    {"q": "Small steps, repeated daily, become extraordinary results.", "a": "Daily Inspiration"},
    {"q": "Your future changes the moment your habits do.", "a": "Daily Inspiration"},
    {"q": "Discipline is quiet. Its results are not.", "a": "Daily Inspiration"},
    {"q": "Progress beats perfection every single day.", "a": "Daily Inspiration"},
    {"q": "Be consistent long enough and luck starts calling it talent.", "a": "Daily Inspiration"},
    {"q": "The right pace is the one you can sustain.", "a": "Daily Inspiration"},
    {"q": "Focus on the work. Let the results surprise you.", "a": "Daily Inspiration"},
    {"q": "A calm mind builds a strong life.", "a": "Daily Inspiration"},
    {"q": "Show up today. That is where momentum starts.", "a": "Daily Inspiration"},
    {"q": "What you repeat becomes what you become.", "a": "Daily Inspiration"},
    {"q": "Better habits create better outcomes.", "a": "Daily Inspiration"},
    {"q": "Do the hard thing while it is still small.", "a": "Daily Inspiration"},
    {"q": "Silence the doubt with steady action.", "a": "Daily Inspiration"},
    {"q": "You do not need perfect days, only honest ones.", "a": "Daily Inspiration"},
    {"q": "Keep going. The version of you that wins is built in public and private.", "a": "Daily Inspiration"},
    {"q": "The quiet work is usually the work that changes everything.", "a": "Daily Inspiration"},
    {"q": "Build a life that makes discipline feel natural.", "a": "Daily Inspiration"},
    {"q": "Success often looks like doing the basics with care.", "a": "Daily Inspiration"},
    {"q": "Less noise. More progress.", "a": "Daily Inspiration"},
    {"q": "Your habits are writing tomorrow before you arrive there.", "a": "Daily Inspiration"},
    {"q": "The strongest momentum starts with one honest decision.", "a": "Daily Inspiration"},
    {"q": "Make the next hour count and the day starts to change.", "a": "Daily Inspiration"},
    {"q": "Consistency is the part that turns effort into identity.", "a": "Daily Inspiration"},
    {"q": "A better routine is a better future in disguise.", "a": "Daily Inspiration"},
    {"q": "Growth is built in the ordinary moments nobody posts about.", "a": "Daily Inspiration"},
    {"q": "What you protect your attention from matters.", "a": "Daily Inspiration"},
    {"q": "Simple goals, repeated well, create powerful change.", "a": "Daily Inspiration"},
    {"q": "One focused day can restart a whole season.", "a": "Daily Inspiration"},
    {"q": "You become reliable by practicing reliability.", "a": "Daily Inspiration"},
    {"q": "Do not wait to feel ready; build readiness by acting.", "a": "Daily Inspiration"},
    {"q": "There is strength in choosing the harder right thing.", "a": "Daily Inspiration"},
    {"q": "If it matters, give it your best ordinary day.", "a": "Daily Inspiration"},
    {"q": "The long game rewards people who keep showing up.", "a": "Daily Inspiration"},
    {"q": "Stay close to what makes you calmer and sharper.", "a": "Daily Inspiration"},
    {"q": "A good day starts before the world asks anything of you.", "a": "Daily Inspiration"},
    {"q": "The most valuable momentum is the kind nobody sees at first.", "a": "Daily Inspiration"},
    {"q": "Keep your standards high and your process steady.", "a": "Daily Inspiration"},
    {"q": "Your energy should build the life you want, not drain it.", "a": "Daily Inspiration"},
    {"q": "Tiny improvements become visible when they are repeated.", "a": "Daily Inspiration"},
    {"q": "Choose the work that makes tomorrow easier.", "a": "Daily Inspiration"},
    {"q": "A focused mind turns effort into direction.", "a": "Daily Inspiration"},
    {"q": "You do not need a louder plan, just a cleaner one.", "a": "Daily Inspiration"},
    {"q": "Quiet consistency is undefeated over time.", "a": "Daily Inspiration"},
    {"q": "Build momentum in the morning and the day follows it.", "a": "Daily Inspiration"},
    {"q": "The most powerful reset is a decision kept simple.", "a": "Daily Inspiration"},
    {"q": "Today is enough when today is used well.", "a": "Daily Inspiration"},
    {"q": "Move with purpose and let the rest catch up.", "a": "Daily Inspiration"},
    {"q": "Clarity grows when distractions get smaller.", "a": "Daily Inspiration"},
    {"q": "What you build daily becomes what you believe about yourself.", "a": "Daily Inspiration"},
    {"q": "Better days often begin with one better choice.", "a": "Daily Inspiration"},
    {"q": "Your future respects consistency more than intensity.", "a": "Daily Inspiration"},
    {"q": "The work becomes lighter when the habit becomes real.", "a": "Daily Inspiration"},
    {"q": "A sharp routine can carry a soft heart.", "a": "Daily Inspiration"},
    {"q": "Keep the standard, keep the pace, keep the promise.", "a": "Daily Inspiration"},
    {"q": "The best version of you is built with repetition.", "a": "Daily Inspiration"},
]


def get_instagram_quote():
    return random.choice(INSTAGRAM_QUOTES)